from typing import Protocol

from pydantic import EmailStr

from server.user.models import User


class UserRepository(Protocol):
    def get_user_by_email(self, email: EmailStr) -> User | None: ...
    def get_user_by_id(self, user_id: int) -> User | None: ...
    def create_user(self, user: User) -> User: ...
    def edit_user(self, user: User) -> User: ...
    def delete_user(self, user: User) -> None: ...
