class OtpExpiredError(Exception): ...


class OtpConsumedError(Exception): ...


class OtpInvalidError(Exception): ...


class UserNotFoundError(Exception): ...


class InvalidChallengeTokenError(Exception): ...
