from pathlib import Path
from typing import Protocol


class ImageRepository(Protocol):
    def write_image(self, image: bytes, relative_path: Path) -> None: ...
    def write_thumbnail(self, image: bytes, relative_path: Path) -> None: ...
    def delete_image(self, relative_path: Path) -> None: ...
    def delete_thumbnail(self, relative_path: Path) -> None: ...
    def list_images(self, base_dir: Path, *, recursive: bool) -> list[Path]: ...
    def read_image(self, relative_path: Path) -> bytes: ...
    def read_thumbnail(self, relative_path: Path) -> bytes: ...
