from pathlib import Path
from typing import Protocol


class ImageRepository(Protocol):
    def write_file(self, image: bytes, full_path: Path) -> None: ...
    def delete_file(self, full_path: Path) -> None: ...
    def list_images(self, base_dir: Path, *, recursive: bool) -> list[Path]: ...
    def read_file(self, full_path: Path) -> bytes: ...
