from pathlib import Path
from typing import Protocol

from PIL.Image import Image

from server.images.models import ImageSearchQuery
from server.index.models import IndexedImage


class ImageService(Protocol):
    def add_image(self, image: bytes, relative_path: Path) -> None: ...
    def add_thumbnail_for_image(self, image_path: Path) -> None: ...
    def remove_image(self, image_id: int) -> None: ...
    def query_images(self, query: ImageSearchQuery) -> list[IndexedImage]: ...
    def similarity_search(self, image: bytes, top_k: int) -> list[IndexedImage]: ...
    def search_by_image(self, image_id: int, top_k: int) -> list[IndexedImage]: ...
    def get_unindexed_images(self) -> list[Path]: ...
    def get_thumbnail_for_image(self, image_id: int) -> Image: ...
