from pathlib import Path
from typing import Protocol
from uuid import UUID

from PIL.Image import Image

from server.images.models import ImageSearchQuery
from server.index.models import IndexedImage


class ImageService(Protocol):
    def add_image(self, image: bytes, relative_path: Path) -> None: ...
    def add_thumbnail_for_image(self, relative_path: Path) -> None: ...
    def remove_image(self, image_id: UUID) -> None: ...
    def remove_thumbnail_for_image(self, relative_path: Path) -> None: ...
    def query_images(self, query: ImageSearchQuery) -> list[IndexedImage]: ...
    def similarity_search(
        self,
        image: Image,
        top_k: int,
        query: ImageSearchQuery,
    ) -> list[IndexedImage]: ...
    def search_by_image(
        self,
        image_id: UUID,
        top_k: int,
        query: ImageSearchQuery,
    ) -> list[IndexedImage]: ...
    def get_unindexed_images(self) -> list[Path]: ...
    def clean_stale_indexed_images(self) -> None: ...
    def get_thumbnail_for_image(self, image_id: UUID) -> Image: ...
    def get_image_by_path(self, image_path: Path) -> IndexedImage | None: ...
    def get_image_by_id(self, image_id: UUID) -> IndexedImage | None: ...
