from pathlib import Path
from typing import Protocol

from PIL.Image import Image

from server.images.models import ImageSearchQuery
from server.index.models import IndexedImage


class ImageService(Protocol):
    def add_image(self, image: bytes, relative_path: Path) -> None: ...
    def add_thumbnail_for_image(self, image_path: Path) -> None: ...
    def remove_image(self, image_id: int) -> None: ...
    def remove_thumbnail_for_image(self, image_path: Path) -> None: ...
    def query_images(self, query: ImageSearchQuery) -> list[IndexedImage]: ...
    def similarity_search(
        self,
        image: Image,
        top_k: int,
        query: ImageSearchQuery | None = None,
    ) -> list[IndexedImage]: ...
    def search_by_image(
        self,
        image_id: int,
        top_k: int,
        query: ImageSearchQuery,
    ) -> list[IndexedImage]: ...
    def get_unindexed_images(self) -> list[Path]: ...
    def clean_stale_indexed_images(self) -> None: ...
    def get_thumbnail_for_image(self, image_id: int) -> Image: ...
    def get_image_by_path(self, image_path: Path) -> IndexedImage | None: ...
    def get_image_by_id(self, image_id: int) -> IndexedImage | None: ...
