from pathlib import Path
from typing import Protocol


class ImageRepository(Protocol):
    def add_image_file(self, image: bytes, relative_path: Path) -> None: ...
    def remove_image_file(self, relative_path: Path) -> None: ...
    def get_images_from_directory(self, relative_dir: Path) -> list[Path]: ...
