from typing import Protocol
from uuid import UUID

from pydantic import EmailStr

from server.user.models import User, UserSearchQuery


class UserRepository(Protocol):
    def get_user_by_email(self, email: EmailStr) -> User | None: ...
    def get_user_by_id(self, user_id: UUID) -> User | None: ...
    def list_users(self, query: UserSearchQuery) -> list[User]: ...
    def create_user(self, user: User) -> User: ...
    def edit_user(self, user: User) -> User: ...
    def delete_user(self, user: User) -> None: ...
    def get_user_count(self) -> int: ...
