from typing import Protocol

from server.user.models import User, UserSearchQuery


class UserService(Protocol):
    def get_user_by_email(self, email: str) -> User | None: ...

    def get_user_by_id(self, user_id: int) -> User | None: ...

    def create_user(self, user: User) -> User: ...

    def update_user(self, user_id: int, new_user: User) -> User: ...
    def delete_user(self, user_id: int) -> None: ...
    def list_users(self, query: UserSearchQuery) -> list[User]: ...
    def get_user_count(self) -> int: ...
